config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      post 'follow/:follow_id' => 'users#follow', as: :follow
      post 'unfollow/:follow_id' => 'users#unfollow', as: :unfollow
    end
  end

  root 'users#index'

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
	self.table_name = "users_subscriptions"
	belongs_to :follower, :class_name => 'User'
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :subscriptions, foreign_key: 'user_id', :dependent => :destroy
	has_many :followers, class_name: 'User', foreign_key: 'follower_id', :through => :subscriptions
	has_and_belongs_to_many :following, class_name: 'User', foreign_key: 'follower_id', :join_table => :users_subscriptions, :dependant => :destroy

	def follow( user_id )
		if user_id != self.id
			Subscription.create(follower_id: self.id, user_id: user_id)
		end
	end

	def unfollow( user_id )
		if user_id != self.id
			sub = Subscription.find_by(follower_id: self.id, user_id: user_id)
			sub.delete
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :follow, :unfollow]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to :users, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  # POST /users/1/follow/1
  def follow
    followed = User.find(params[:follow_id])
    if followed && @user
      @user.follow(followed.id)
    end
    render json: @user.followers
  end

  # POST /users/1/unfollow/1
  def unfollow
    followed = User.find(params[:follow_id])
    if followed && @user
      @user.unfollow(followed.id)
    end
    render json: @user.followers
  end


  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RevalApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<table>
  <thead>
    <tr>
      <th>Following</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.following.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><button onclick="subscribe( '<%= unfollow_user_path(@user.id, user.id) %>' )">Unfollow</button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<table>
  <thead>
    <tr>
      <th>Followers</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.followers.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<table>
  <thead>
    <tr>
      <th>Not Following</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% ((User.all - [@user]) - @user.following).each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><button onclick="subscribe( '<%= follow_user_path(@user.id, user.id) %>' )">Follow</button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
<script>
function subscribe(url)
{
	$.ajax({
	  		type: "POST",
	  		url: url
	  	})
	  	.done(function() {
	    	alert( "success" );
	  	})
	  	.fail(function() {
	    	alert( "Failure!" );
  	});
}
</script>